[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
startCommand = "npm start"

[[deploy.environmentVariables]]
name = "NODE_ENV"
value = "production" 